In [1]:
##51
import numpy as np

dtype = np.dtype([('position', '2f4'), ('color', '3i4')])

arr = np.array([((1.0, 2.0), (255, 0, 0)),
                ((3.0, 4.0), (0, 255, 0)),
                ((5.0, 6.0), (0, 0, 255))], dtype=dtype)

print(arr)


[([1., 2.], [255,   0,   0]) ([3., 4.], [  0, 255,   0])
 ([5., 6.], [  0,   0, 255])]


In [2]:
##52
import numpy as np

points = np.random.rand(100, 2)

distances = np.linalg.norm(points[1:] - points[:-1], axis=1)

print(distances)


[0.75830652 0.57567706 0.74821025 0.59602108 0.41726932 0.56637011
 0.10005963 0.06520208 0.52061349 0.37143118 0.28756038 0.41611062
 0.66444407 0.50403831 0.5123643  0.68115909 0.48320266 0.74020854
 0.47263647 0.46419042 0.35636516 0.48090555 0.20724206 0.52202778
 0.65459362 0.90493379 1.08779073 0.91731345 0.6337641  0.61048335
 0.79040452 0.55702138 0.186632   0.24707032 0.77075132 0.83356216
 0.23050017 0.71393524 0.53569112 0.45548125 0.73515288 0.68384626
 0.06986125 0.63715342 0.53612045 0.48169791 0.95682292 0.22480161
 0.23259767 0.50287568 0.64409564 0.28051585 0.26507975 0.78885159
 0.38290221 0.53740047 0.20758077 0.45582561 0.52036577 0.71868665
 0.63284487 0.25682781 0.78458287 0.56798466 0.9763105  0.53948636
 0.85521904 0.36637933 0.22996063 0.52446696 0.386239   0.73773154
 0.89085058 0.2741114  0.50354447 0.8477072  0.7425888  0.60989504
 0.52803666 0.489773   0.32684165 0.7359656  0.81337011 0.38607436
 0.19069065 0.43961848 0.85143238 0.53648402 0.36157339 1.0101

In [3]:
##53
import numpy as np

arr = np.array([1.2, 2.5, 3.7], dtype=np.float32)

arr = arr.astype(np.int32)

print(arr)


[1 2 3]


In [4]:
##54

import numpy as np

arr = np.genfromtxt('data.csv', delimiter=',', filling_values=np.nan)

print(arr)


FileNotFoundError: data.csv not found.

In [5]:
##55
import numpy as np

arr = np.array([10, 20, 30, 40])

for idx, value in np.ndenumerate(arr):
    print(f"Index: {idx}, Value: {value}")



Index: (0,), Value: 10
Index: (1,), Value: 20
Index: (2,), Value: 30
Index: (3,), Value: 40


In [6]:
##56
import numpy as np

mean = 0
std_dev = 1
shape = (5, 5)

gaussian_array = np.random.normal(mean, std_dev, shape)

print(gaussian_array)


[[-1.42512257  0.25916003  2.12699184  0.27214671 -0.36990388]
 [-0.62402603  2.05588451  0.16026236  0.35223506 -1.37134282]
 [-0.82664611 -0.16248721  0.276253    1.65882664  0.35073155]
 [ 1.21390799  0.26538213 -0.42809609 -2.0868538  -0.6428009 ]
 [ 0.05138662  0.11466407 -0.70930943 -0.54639392 -0.08516594]]


In [7]:
##57
import numpy as np

array = np.zeros((5, 5))

p = 5

indices = np.random.choice(array.size, p, replace=False)
np.put(array, indices, 1)

print(array)


[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1.]]


In [ ]:
##58
import numpy as np

matrix = np.random.rand(3, 4)


matrix_centered = matrix - matrix.mean(axis=1, keepdims=True)

print(matrix_centered)


In [ ]:
##59
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sorted_array = array[array[:, 1].argsort()]

print(sorted_array)


In [ ]:
##60
import numpy as np

array = np.array([[1, np.nan, 3], [4, np.nan, 6], [7, np.nan, 9]])

null_columns = np.any(np.isnan(array), axis=0)

print(null_columns)  


In [ ]:
##61
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

target = 32
nearest_value = arr[np.abs(arr - target).argmin()]

print(nearest_value)


In [ ]:
##62
import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])

for x, y in np.nditer([arr1, arr2]):
    print(x + y)


In [ ]:
##63
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, shape, dtype, name):
        obj = super().__new__(cls, shape, dtype)
        obj.name = name
        return obj

arr = NamedArray((2, 2), dtype=int, name="MyArray")

print(arr.name)  


In [ ]:
##64
import numpy as np

vec = np.array([0, 0, 0, 0, 0])

indices = np.array([1, 3, 4])

np.add.at(vec, indices, 1)

print(vec)


In [ ]:
##65
import numpy as np

X = np.array([1, 2, 3])
I = np.array([0, 2, 1])
F = np.zeros(3)

np.add.at(F, I, X)

print(F)


In [ ]:
##66
import numpy as np

w, h = 5, 5
image = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)

reshaped_image = image.reshape((-1, 3))

unique_colors = np.unique(reshaped_image, axis=0)

print(len(unique_colors))  


In [ ]:
##67
import numpy as np

array = np.random.rand(2, 3, 4, 5)

sum_result = array.sum(axis=(-2, -1))

print(sum_result)


In [ ]:
##68
import numpy as np

D = np.array([1, 2, 3, 4, 5])
S = np.array([0, 1, 0, 1, 0])

unique_indices = np.unique(S)
means = [D[S == idx].mean() for idx in unique_indices]

print(means)


In [ ]:
##69
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
diagonal = np.diagonal(dot_product)

print(diagonal)


In [ ]:
##70
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

new_arr = np.zeros(len(arr) * 4 - 3, dtype=int)
new_arr[::4] = arr

print(new_arr)


In [ ]:
##71
import numpy as np

array1 = np.random.rand(5, 5, 3)
array2 = np.random.rand(5, 5)

result = array1 * array2[:, :, None]

print(result)


In [ ]:
##72
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

array[[1, 3]] = array[[3, 1]]

print(array)


In [ ]:
##73
import numpy as np

triangles = np.array([
    [(0, 0), (1, 0), (0, 1)],
    [(1, 0), (2, 0), (1, 1)],
    [(0, 1), (1, 1), (0, 2)],
    [(2, 0), (3, 0), (2, 1)],
    [(1, 1), (2, 1), (1, 2)],
    [(0, 2), (1, 2), (0, 3)],
    [(3, 0), (4, 0), (3, 1)],
    [(2, 1), (3, 1), (2, 2)],
    [(1, 2), (2, 2), (1, 3)],
    [(3, 1), (4, 1), (3, 2)],
])

edges = set()
for triangle in triangles:
    for i in range(3):
        edge = tuple(sorted([triangle[i], triangle[(i + 1) % 3]]))
        edges.add(edge)

print(np.array(list(edges)))


In [ ]:
##74
import numpy as np

C = np.array([0, 2, 3, 4])

A = np.repeat(np.arange(len(C)), C)
print(A)


In [ ]:
##75
import numpy as np

def sliding_window_avg(arr, window_size):
    return np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

arr = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 3
print(sliding_window_avg(arr, window_size))


In [ ]:
##76
import numpy as np

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 3

result = np.array([Z[i:i + window_size] for i in range(len(Z) - window_size + 1)])

print(result)


In [ ]:
##77
import numpy as np

bool_array = np.array([True, False, True])
bool_array = ~bool_array
print(bool_array)

float_array = np.array([1.2, -3.4, 5.6])
float_array = -float_array
print(float_array)


In [ ]:
##78
import numpy as np

def point_to_line_distance(p, P0, P1):
    return np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0)

P0 = np.array([[1, 1], [3, 3], [5, 5]])
P1 = np.array([[2, 2], [4, 4], [6, 6]])
p = np.array([3, 1])

distances = [point_to_line_distance(p, p0, p1) for p0, p1 in zip(P0, P1)]
print(distances)


In [ ]:
##79
import numpy as np

def point_to_line_distance(p, P0, P1):
    return np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0)

P0 = np.array([[1, 1], [3, 3], [5, 5]])
P1 = np.array([[2, 2], [4, 4], [6, 6]])
P = np.array([[3, 1], [2, 3]])

distances = [[point_to_line_distance(p, p0, p1) for p0, p1 in zip(P0, P1)] for p in P]
print(np.array(distances))


In [ ]:
##80
import numpy as np

def extract_subarray(arr, center, shape, fill_value=0):
    start = np.array(center) - np.array(shape) // 2
    end = start + shape
    slices = tuple(slice(max(s, 0), min(e, arr.shape[i])) for i, (s, e) in enumerate(zip(start, end)))
    subarray = np.zeros(shape, dtype=arr.dtype) + fill_value
    subarray[tuple(slice(max(0, s), e) for s, e in zip(start, end))] = arr[slices]
    return subarray

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subarray = extract_subarray(arr, (1, 1), (3, 3), fill_value=0)
print(subarray)


In [ ]:
##81
import numpy as np

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])
print(R)


In [ ]:
##82
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
rank = np.linalg.matrix_rank(A)
print(rank)


In [ ]:
##83
import numpy as np
from scipy import stats

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
mode = stats.mode(arr)[0][0]
print(mode)


In [ ]:
##84
import numpy as np

matrix = np.random.rand(10, 10)
blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, 3, 3), strides=matrix.strides * 2)
print(blocks)


In [ ]:
##85
import numpy as np

class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        if i != j:
            super().__setitem__((j, i), value)
        super().__setitem__(index, value)

Z = np.zeros((3, 3), dtype=int).view(SymmetricArray)
Z[0, 1] = 5
print(Z)


In [ ]:
##86
import numpy as np

matrices = np.random.rand(5, 3, 3)
vectors = np.random.rand(5, 3, 1)

result = np.sum([np.dot(m, v) for m, v in zip(matrices, vectors)], axis=0)
print(result)


In [ ]:
##87
import numpy as np

matrix = np.random.rand(16, 16)
block_size = 4

block_sum = matrix.reshape(4, 4, 4, 4).sum(axis=(2, 3))
print(block_sum)


In [ ]:
##88
import numpy as np

def game_of_life(grid, steps):
    for _ in range(steps):
        neighbor_count = sum(np.roll(np.roll(grid, i, axis=0), j, axis=1) for i in [-1, 0, 1] for j in [-1, 0, 1])
        grid = (neighbor_count == 3) | (grid & (neighbor_count == 2))
    return grid

grid = np.random.randint(0, 2, (5, 5))
steps = 10
grid_after = game_of_life(grid, steps)
print(grid_after)


In [ ]:
##89
import numpy as np

Z = np.random.randint(0, 100, 10)
n = 3
print(np.sort(Z)[-n:])  
print(Z[np.argpartition(-Z, n)[:n]])  



In [ ]:
##90
from itertools import product

arrays = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
cartesian_prod = np.array(list(product(*arrays)))
print(cartesian_prod)


In [ ]:
##91
Z = np.array([(1, 2.0, 'Hello'), (2, 3.0, 'World')],
             dtype=[('x', int), ('y', float), ('z', 'U10')])
print(Z)


In [ ]:
##92
Z = np.random.rand(5)
print(Z ** 3)           
print(np.power(Z, 3))   
print(np.einsum('i,i,i->i', Z, Z, Z))  


In [ ]:
##93
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))
mask = np.all(np.isin(A[:, None, :], B), axis=(1, 2))
print(A[mask])


In [ ]:
##94
Z = np.random.randint(0, 5, (10, 3))
print(Z[~(Z[:, 0] == Z[:, 1]) | (Z[:, 1] == Z[:, 2])])


In [ ]:
##95
Z = np.array([3, 7, 8])
print(((Z[:, None] & (1 << np.arange(8))) > 0).astype(int))


In [ ]:
##96
Z = np.random.randint(0, 5, (6, 3))
print(np.unique(Z, axis=0))


In [ ]:
##97
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

inner = np.einsum('i,i->', A, B)
outer = np.einsum('i,j->ij', A, B)
sum_ = np.einsum('i->', A)
mul = np.einsum('i,i->i', A, B)

print(inner, outer, sum_, mul)


In [ ]:
##98
X, Y = np.random.rand(10), np.random.rand(10)
from scipy.interpolate import interp1d

distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumdist = np.insert(np.cumsum(distances), 0, 0)
f_x = interp1d(cumdist, X, kind='linear')
f_y = interp1d(cumdist, Y, kind='linear')

uniform_samples = np.linspace(0, cumdist[-1], 10)
X_new, Y_new = f_x(uniform_samples), f_y(uniform_samples)
print(X_new, Y_new)


In [ ]:
##99
X = np.random.randint(0, 4, (10, 3))
n = 5
valid_rows = np.all(X >= 0, axis=1) & (np.sum(X, axis=1) == n)
print(X[valid_rows])


In [ ]:
##100
X = np.random.randn(1000)
N = 1000
means = np.random.choice(X, (N, X.size), replace=True).mean(axis=1)
conf_int = np.percentile(means, [2.5, 97.5])
print(conf_int)
